openapi: 3.0.0
info:
  title: Friends API
  version: 1.0.0
paths:
  /friends:
    post:
      summary: Create a friend
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                age:
                  type: integer
      responses:
        '201':
          description: Friend created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  age:
                    type: integer
        '400':
          description: Bad request
    get:
      summary: Get all friends
      responses:
        '200':
          description: A list of friends
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    age:
                      type: integer
        '500':
          description: Server error